import pygame

SQUARE_SIZE = 40
ROWS, COLS = 20, 25
GRID_WIDTH = SQUARE_SIZE * COLS
GRID_HEIGHT = SQUARE_SIZE * ROWS
CONTROL_WIDTH = 150
CONTROL_HEIGHT = GRID_HEIGHT
TOTAL_WIDTH = GRID_WIDTH + CONTROL_WIDTH
TOTAL_HEIGHT = GRID_HEIGHT + CONTROL_HEIGHT
SLEEP_TIME = 0.1

# types of buttons
TYPE_START = 'Start'
TYPE_END = 'End'
TYPE_WALL = 'Walls'
TYPE_REMOVE = 'Remove'
TYPE_GO = 'Go'
TYPE_RESET = 'Reset'

# control panel button positions
BTN_WIDTH, BTN_HEIGHT = 100, 50
START_POS_X = END_POS_X = WALL_POS_X = REMOVE_POS_X = GO_POS_X = RESET_POS_X = TOTAL_WIDTH - (TOTAL_WIDTH - GRID_WIDTH) + (((TOTAL_WIDTH - GRID_WIDTH) - BTN_WIDTH) // 2)
START_POS_Y = 25
END_POS_Y = 125
WALL_POS_Y = 225
REMOVE_POS_Y = 325
GO_POS_Y = 525
RESET_POS_Y = 625

# colours in rgb
LIGHT_GREY = (192, 192, 192)
GREY = (96, 96, 96)
DARK_GREY = (32, 32, 32)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BROWN = (102, 51, 0)
YELLOW = (255, 255, 0)